[package]
name = "scrape_url"
version = "0.1.0"
edition = "2024"

[dependencies]
html2md = "0.2.15"
reqwest = { version = "0.12.15", features = ["blocking"]}
tokio = { version = "1.45.0", features = ["full"] }
